name: Firebase Deployment

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Build & Deployment
    runs-on: ubuntu-latest

    steps:
      - name: get the source code to the container
        uses: actions/checkout@v2

      - name: install node inside the container
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
 
      - name: install dependencies
        run: npm install

      - name: build the react app
        run: npm run build
        env:
          CI: false

      - name: deploy the build folder to firebase 
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}